version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "myRealStrongPass"]
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    image: ai-planner:latest
    container_name: ai-planner-app
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    command: >
      bash -c "./scripts/run_migrations.sh &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000"
  worker:
    build: .
    image: ai-planner:latest
    container_name: ai-planner-worker
    env_file:
      - .env.production
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    command: python worker.py

networks:
  default:
    driver: bridge

volumes:
  mongo_data: { }
